version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8003:8000"
    env_file:
        - .env
    volumes:
        - .:/var/www
    networks:
      - app-network
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=auto-news
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ir7mEa3Yj4uAc
    ports:
      - "8432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
        - app-network
volumes:
  db:
networks:
    app-network:
        driver: bridge
